{{- if or .Values.secrets.databaseUrl .Values.secrets.redisUrl .Values.secrets.jwtSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "armature.fullname" . }}-secrets
  labels:
    {{- include "armature.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.redisUrl }}
  redis-url: {{ .Values.secrets.redisUrl | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecret }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  {{- end }}
{{- end }}

